### ISSUE TITLE
Update overview video to reflect new class format

### ISSUE THREAD

**Issue by shrutivanw** [Ada-Developers-Academy/jump-start-live#14]
The "Overview video" under https://github.com/Ada-Developers-Academy/jump-start-live#resources needs to be updated to reflect the new format (additional prep work before class and more focus on discussions during class).

For now, to avoid student confusion (until we have the updated video), the link to the overview video has been removed:
| [Overview Video](https://adaacademy.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1c9d71c0-7952-48ab-a55b-b29b25066509) | ~4 min video overview of JumpStart Live |

**Comment by susanev** [comment]
@shrutivanw is this something you or Brooks is taking on?

**Comment by shrutivanw** [comment]
@susanev yes, we will. Thanks for checking.

**Comment by CheezItMan** [comment]
@shrutivanw 
I'd updated the video earlier this week.
